-- ============================================
-- TradR Supabase Schema (Fantasy + Real Money)
-- Run this entire file in Supabase SQL Editor
-- ============================================

-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Profiles table (linked to auth.users)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  username text,
  balance numeric(12,2) default 100.00,   -- starter balance for demo (real money balance)
  created_at timestamptz default now()
);

-- Contests
create table if not exists contests (
  id bigint generated by default as identity primary key,
  title text not null,
  entry_fee numeric(10,2) not null,
  first_prize numeric(10,2) not null,
  total_prizes numeric(10,2) not null,
  max_entries integer,
  status text default 'open' check (status in ('open','active','closed')),
  starting_portfolio numeric(12,2) default 100000,
  assets text[] default '{}',
  ends_at timestamptz,
  created_at timestamptz default now()
);

-- Participations: user's virtual portfolio in a contest
create table if not exists participations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  contest_id bigint references contests on delete cascade not null,
  cash numeric(12,2) default 100000,           -- virtual cash
  positions jsonb default '[]'::jsonb,          -- e.g. [{"symbol":"NVDA","shares":120,"avgPrice":128.5}]
  starting_value numeric(12,2),
  final_value numeric(12,2),
  final_rank integer,
  payout numeric(12,2) default 0,
  created_at timestamptz default now(),
  unique(user_id, contest_id)
);

-- Trade log (virtual portfolio trades — separate from real-money transactions)
create table if not exists trade_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  contest_id bigint references contests on delete cascade not null,
  symbol text not null,
  side text not null check (side in ('buy','sell')),
  shares numeric(12,4) not null,
  price numeric(12,4) not null,
  total numeric(12,2) not null,
  created_at timestamptz default now()
);

-- Transactions (real money side: deposits, entry fees, payouts)
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  type text not null check (type in ('deposit','entry_fee','payout','withdrawal')),
  amount numeric(12,2) not null,
  description text,
  contest_id bigint references contests,
  created_at timestamptz default now()
);

-- ============================================
-- Row Level Security (RLS) - IMPORTANT
-- ============================================

alter table contests enable row level security;
alter table profiles enable row level security;
alter table participations enable row level security;
alter table transactions enable row level security;
alter table trade_log enable row level security;

-- Contests (public read for lobby)
create policy "Public can view contests"
  on contests for select using (true);

-- Profiles
create policy "Authenticated users can view profiles"
  on profiles for select using (auth.uid() is not null);

create policy "Users can update own profile"
  on profiles for update using (auth.uid() = id);

-- Participations (leaderboard requires reading all entries in a contest)
create policy "Authenticated users can view participations"
  on participations for select using (auth.uid() is not null);

create policy "Users can insert own participations"
  on participations for insert with check (auth.uid() = user_id);

create policy "Users can update own participations"
  on participations for update using (auth.uid() = user_id);

-- Transactions
create policy "Users can view own transactions"
  on transactions for select using (auth.uid() = user_id);

create policy "Users can insert own transactions"
  on transactions for insert with check (auth.uid() = user_id);

-- Trade log
create policy "Users can view own trades"
  on trade_log for select using (auth.uid() = user_id);

create policy "Users can insert own trades"
  on trade_log for insert with check (auth.uid() = user_id);

-- ============================================
-- Auto-create profile on signup
-- ============================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, balance, referral_code)
  values (
    new.id,
    split_part(new.email, '@', 1),
    100.00,
    'pit' || left(replace(new.id::text, '-', ''), 8)
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================
-- Seed some demo contests (optional)
-- ============================================

alter table contests add column if not exists slug text;
alter table contests add column if not exists tagline text;
alter table contests add column if not exists badge text;

insert into contests (title, slug, tagline, badge, entry_fee, first_prize, total_prizes, max_entries, status, starting_portfolio, assets, ends_at)
values
  ('Opening Bell Pit', 'opening-bell', 'Free daily — when the bell rings, the pit opens.', 'FREE DAILY', 0, 50, 200, 500, 'open', 100000, ARRAY['SPY','QQQ','BTC','ETH'], now() + interval '20 hours'),
  ('The Liquidation', 'the-liquidation', 'Paid daily drop. Only the ruthless survive.', 'DAILY DROP', 5, 125, 500, 120, 'open', 100000, ARRAY['SPY','QQQ','NVDA','BTC','ETH'], now() + interval '1 day'),
  ('Full Send Pit', 'full-send', 'No brakes. Max conviction. Enter the chaos.', 'HIGH STAKES', 10, 200, 440, 55, 'open', 100000, ARRAY['AAPL','TSLA','BTC','SOL','DOGE'], now() + interval '1 day'),
  ('Triple Stack Pit', 'triple-stack', 'Three positions. Triple the pressure.', '3X HEAT', 10, 180, 400, 80, 'open', 100000, ARRAY['NVDA','META','BTC'], now() + interval '1 day'),
  ('Weekend Carnage', 'weekend-carnage', 'Saturday slaughter. Sunday survivors.', 'WEEKEND', 10, 250, 600, 100, 'open', 100000, ARRAY['SPY','TSLA','BTC','ETH','SOL'], now() + interval '2 days'),
  ('TradFi vs Degen Pit', 'tradfi-vs-degen', 'NYSE suits vs on-chain chaos. Pick your side.', 'RIVALRY', 5, 85, 380, 150, 'open', 100000, ARRAY['SPY','META','BTC','ETH','SOL'], now() + interval '6 hours')
on conflict do nothing;

-- ============================================
-- Atomic game functions (server-side truth)
-- ============================================

create or replace function public.join_contest(p_contest_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_contest contests%rowtype;
  v_balance numeric;
  v_count integer;
  v_new_balance numeric;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select * into v_contest from contests where id = p_contest_id for update;
  if not found then raise exception 'Contest not found'; end if;
  if v_contest.status = 'closed' then raise exception 'Contest is closed'; end if;

  select count(*) into v_count from participations where contest_id = p_contest_id;
  if v_contest.max_entries is not null and v_count >= v_contest.max_entries then
    raise exception 'Contest is full';
  end if;

  if exists (select 1 from participations where user_id = v_user_id and contest_id = p_contest_id) then
    raise exception 'Already joined this contest';
  end if;

  select balance into v_balance from profiles where id = v_user_id for update;
  if v_balance is null then raise exception 'Profile not found'; end if;
  if v_balance < v_contest.entry_fee then raise exception 'Insufficient balance'; end if;

  v_new_balance := v_balance - v_contest.entry_fee;
  update profiles set balance = v_new_balance where id = v_user_id;

  insert into participations (user_id, contest_id, cash, positions, starting_value)
  values (v_user_id, p_contest_id, v_contest.starting_portfolio, '[]'::jsonb, v_contest.starting_portfolio);

  insert into transactions (user_id, type, amount, description, contest_id)
  values (v_user_id, 'entry_fee', -v_contest.entry_fee, 'Entry for ' || v_contest.title, p_contest_id);

  update contests set status = 'active' where id = p_contest_id and status = 'open';

  return jsonb_build_object(
    'success', true,
    'new_balance', v_new_balance,
    'entry_count', v_count + 1
  );
end;
$$;

create or replace function public.execute_trade(
  p_contest_id bigint,
  p_symbol text,
  p_side text,
  p_shares numeric,
  p_price numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_part participations%rowtype;
  v_contest contests%rowtype;
  v_positions jsonb;
  v_cash numeric;
  v_cost numeric;
  v_elem jsonb;
  v_i int;
  v_old_shares numeric;
  v_old_avg numeric;
  v_new_shares numeric;
  v_new_avg numeric;
  v_found boolean := false;
  v_new_positions jsonb := '[]'::jsonb;
begin
  if v_user_id is null then raise exception 'Not authenticated'; end if;
  if p_shares <= 0 then raise exception 'Invalid share amount'; end if;
  if p_side not in ('buy', 'sell') then raise exception 'Invalid trade side'; end if;
  if p_price <= 0 then raise exception 'Invalid price'; end if;

  select * into v_contest from contests where id = p_contest_id;
  if not found then raise exception 'Contest not found'; end if;
  if v_contest.status = 'closed' then raise exception 'Contest is closed'; end if;
  if v_contest.assets is null or not (p_symbol = any(v_contest.assets)) then
    raise exception 'Symbol not allowed in this contest';
  end if;

  select * into v_part from participations
  where user_id = v_user_id and contest_id = p_contest_id for update;
  if not found then raise exception 'You are not in this contest'; end if;

  v_cash := v_part.cash;
  v_positions := coalesce(v_part.positions, '[]'::jsonb);
  v_cost := round(p_shares * p_price, 2);

  if p_side = 'buy' then
    if v_cash < v_cost then raise exception 'Insufficient cash'; end if;
    v_cash := v_cash - v_cost;

    for v_i in 0..jsonb_array_length(v_positions) - 1 loop
      v_elem := v_positions->v_i;
      if v_elem->>'symbol' = p_symbol then
        v_old_shares := (v_elem->>'shares')::numeric;
        v_old_avg := (v_elem->>'avgPrice')::numeric;
        v_new_shares := v_old_shares + p_shares;
        v_new_avg := (v_old_shares * v_old_avg + v_cost) / v_new_shares;
        v_new_positions := v_new_positions || jsonb_build_array(
          jsonb_build_object('symbol', p_symbol, 'shares', v_new_shares, 'avgPrice', v_new_avg)
        );
        v_found := true;
      else
        v_new_positions := v_new_positions || jsonb_build_array(v_elem);
      end if;
    end loop;

    if not v_found then
      v_new_positions := v_new_positions || jsonb_build_array(
        jsonb_build_object('symbol', p_symbol, 'shares', p_shares, 'avgPrice', p_price)
      );
    end if;
  else
    for v_i in 0..jsonb_array_length(v_positions) - 1 loop
      v_elem := v_positions->v_i;
      if v_elem->>'symbol' = p_symbol then
        v_old_shares := (v_elem->>'shares')::numeric;
        if v_old_shares < p_shares then raise exception 'Insufficient shares'; end if;
        v_cash := v_cash + v_cost;
        v_new_shares := v_old_shares - p_shares;
        if v_new_shares > 0.0001 then
          v_new_positions := v_new_positions || jsonb_build_array(
            jsonb_build_object('symbol', p_symbol, 'shares', v_new_shares, 'avgPrice', (v_elem->>'avgPrice')::numeric)
          );
        end if;
        v_found := true;
      else
        v_new_positions := v_new_positions || jsonb_build_array(v_elem);
      end if;
    end loop;
    if not v_found then raise exception 'No position to sell'; end if;
  end if;

  update participations
  set cash = round(v_cash, 2), positions = v_new_positions
  where user_id = v_user_id and contest_id = p_contest_id;

  insert into trade_log (user_id, contest_id, symbol, side, shares, price, total)
  values (v_user_id, p_contest_id, p_symbol, p_side, p_shares, p_price, v_cost);

  return jsonb_build_object(
    'cash', round(v_cash, 2),
    'positions', v_new_positions
  );
end;
$$;

grant execute on function public.join_contest(bigint) to authenticated;
grant execute on function public.execute_trade(bigint, text, text, numeric, numeric) to authenticated;