-- Run this in Supabase SQL Editor if you already ran the original schema.
-- Adds multiplayer server-truth layer on top of existing TradR tables.

alter table contests add column if not exists assets text[] default '{}';

alter table participations add column if not exists final_value numeric(12,2);
alter table participations add column if not exists final_rank integer;
alter table participations add column if not exists payout numeric(12,2) default 0;

create table if not exists trade_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  contest_id bigint references contests on delete cascade not null,
  symbol text not null,
  side text not null check (side in ('buy','sell')),
  shares numeric(12,4) not null,
  price numeric(12,4) not null,
  total numeric(12,2) not null,
  created_at timestamptz default now()
);

alter table contests enable row level security;
alter table trade_log enable row level security;

drop policy if exists "Public can view contests" on contests;
create policy "Public can view contests" on contests for select using (true);

drop policy if exists "Users can view own profile" on profiles;
drop policy if exists "Authenticated users can view profiles" on profiles;
create policy "Authenticated users can view profiles" on profiles for select using (auth.uid() is not null);

drop policy if exists "Users can view own participations" on participations;
drop policy if exists "Authenticated users can view participations" on participations;
create policy "Authenticated users can view participations" on participations for select using (auth.uid() is not null);

drop policy if exists "Users can view own trades" on trade_log;
create policy "Users can view own trades" on trade_log for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own trades" on trade_log;
create policy "Users can insert own trades" on trade_log for insert with check (auth.uid() = user_id);

update contests set assets = ARRAY['SPY','QQQ','NVDA','BTC','ETH'], ends_at = coalesce(ends_at, now() + interval '1 day') where title = 'Macro Royale';
update contests set assets = ARRAY['AAPL','TSLA','BTC','SOL','DOGE'], ends_at = coalesce(ends_at, now() + interval '1 day') where title = 'Double Up';
update contests set assets = ARRAY['SPY','META','BTC','ETH','SOL'], ends_at = coalesce(ends_at, now() + interval '6 hours') where title = 'Wall Street vs Crypto';

-- Atomic game functions (same as supabase-schema.sql)
-- Paste lines 153-315 from supabase-schema.sql here, or run the full schema file on a fresh project.