-- Run this in Supabase Dashboard → SQL Editor
-- Adds join_contest + execute_trade RPC functions (required for multiplayer)

-- Trade log (if missing)
create table if not exists trade_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  contest_id bigint references contests on delete cascade not null,
  symbol text not null,
  side text not null check (side in ('buy','sell')),
  shares numeric(12,4) not null,
  price numeric(12,4) not null,
  total numeric(12,2) not null,
  created_at timestamptz default now()
);

alter table trade_log enable row level security;

drop policy if exists "Users can view own trades" on trade_log;
create policy "Users can view own trades" on trade_log for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own trades" on trade_log;
create policy "Users can insert own trades" on trade_log for insert with check (auth.uid() = user_id);

-- Contest assets column (if missing)
alter table contests add column if not exists assets text[] default '{}';

update contests set assets = ARRAY['SPY','QQQ','NVDA','BTC','ETH'] where title = 'Macro Royale' and (assets is null or assets = '{}');
update contests set assets = ARRAY['AAPL','TSLA','BTC','SOL','DOGE'] where title = 'Double Up' and (assets is null or assets = '{}');
update contests set assets = ARRAY['SPY','META','BTC','ETH','SOL'] where title = 'Wall Street vs Crypto' and (assets is null or assets = '{}');

-- Paste join_contest + execute_trade from supabase-schema.sql lines 153-315, then:
-- grant execute on function public.join_contest(bigint) to authenticated;
-- grant execute on function public.execute_trade(bigint, text, text, numeric, numeric) to authenticated;